### PR TITLE
BS-14409 Update 7.2 target platform

### PR DESCRIPTION
**Pull request by rbioteau**
- Add M2e
- Add Groovy M2e integration
- Add Spock
- Add m2 jdt connector

Mirror push on repositories.rd.lan

https://github.com/bonitasoft/bonita-internal-tools/pull/14

### CODE REVIEW

**Comment by apupier** [comment]
the mirror seems not yet correct, it misses all the plugins and features: http://repositories.rd.lan/p2/7.2/
[DIR]	Parent Directory	 	-	 
[   ]	artifacts.jar	29-Sep-2015 11:15	487K	 
[   ]	content.jar	29-Sep-2015 11:15	2.4M

**Comment by rbioteau** [comment]
Fix permissions

**Comment by rbioteau** [comment]
Sadly there is no PR jobs to build platform... :sob:

**Comment by apupier** [comment]
need to update also  bonita-internal-tools

**Pull request merged**
