### PR TITLE
BS-13742: add a validation message to warn user about model inconsitency

### PR DESCRIPTION
**Pull request by apupier**
when Form Mapping are defined at diagram level.

### CODE REVIEW

**Comment by apupier** [comment]
/!\ WAITING for text validation by Chris

**Comment by rbioteau** [comment]
Can you add the specific test case ?

**Comment by apupier** [comment]
Messages are not loaded in unit test so I can just check that we a failure status, not sure ti is really worthing

**Comment by rbioteau** [comment]
You can tests Messages.myKey

**Pull request merged**
