### PR TITLE
BS-14131 Script generation with deep bdm.

### PR DESCRIPTION
**Pull request by rbioteau**
Refactor to handle a context instead of having big constructor.
Add hierarchy in Initializers to retrieve parent variable names.

:warning:  Wait 7.1.1 release before merging

### CODE REVIEW

**Comment by apupier** [comment]
In a deep one-child everytime, When I uncheck parent element and then check a child element, the parent is no more selected.
The good side is that it seems more coherent on what it is done internally as when generating scripts, it doesn't in this case from the 7.1

**Comment by apupier** [comment]
need to synchronize with https://github.com/bonitasoft/bonita-studio/pull/290 which handles the issue (exactly the same?)

**Comment by rbioteau** [comment]
Are you talking about a UI issue ?

**Comment by apupier** [comment]
yes. I merged   what Aurelie did. I will need to test again if modifications on each side are compatible

**Pull request merged**
